#!/bin/bash -e

# Copyright 2015 basebuilder authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/deploy
source ${SOURCE_DIR}/config

if [ -f ${CURRENT_DIR}/.ruby-version -a "${RUBY_VERSION}" == "" ]; then
    RUBY_VERSION=$(cat ${CURRENT_DIR}/.ruby-version)
    rbenv global $RUBY_VERSION
fi

echo "-- Using ruby version: ${RUBY_VERSION} --"

gem update --system
gem install bundler --no-rdoc --no-ri

if [ -f ${CURRENT_DIR}/Gemfile ]; then
    pushd $CURRENT_DIR && bundle install --deployment --path ${CURRENT_DIR}/../vendor/bundle --without ${BUNDLE_WITHOUT-development:test}
    popd
fi
