#!/bin/bash -e

# Copyright 2015 basebuilder authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

SOURCE_DIR=/var/lib/tsuru
$SOURCE_DIR/base/install

apt-get update

apt-get install -qqy autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm3 libgdbm-dev
git clone https://github.com/sstephenson/rbenv.git /home/ubuntu/.rbenv
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> /home/ubuntu/.bash_profile
echo 'eval "$(rbenv init -)"' >> /home/ubuntu/.bash_profile
git clone https://github.com/sstephenson/ruby-build.git /home/ubuntu/.rbenv/plugins/ruby-build
sudo chown ubuntu:ubuntu /home/ubuntu/.bash_profile
sudo chown -R ubuntu:ubuntu /home/ubuntu/.rbenv
/bin/su - ubuntu -c "rbenv install 2.2.2 -v"
/bin/su - ubuntu -c "rbenv install 2.2.3 -v"
/bin/su - ubuntu -c "rbenv install 1.9.3-p551 -v"