#!/bin/bash -el

# Copyright 2015 basebuilder authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

echo 'PATH=/opt/pypy3-2.4.0-linux64/bin/:$PATH' >> /home/ubuntu/.profile
