#!/bin/bash

# Copyright 2015 basebuilder authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

ACTIVATOR_VERSION="1.3.2"

/var/lib/tsuru/base/install

apt-get install unzip software-properties-common -y

echo "Downloading activator..."

cd /tmp
wget http://downloads.typesafe.com/typesafe-activator/${ACTIVATOR_VERSION}/typesafe-activator-${ACTIVATOR_VERSION}.zip
unzip typesafe-activator-${ACTIVATOR_VERSION}.zip
rm typesafe-activator-${ACTIVATOR_VERSION}.zip
mv activator-${ACTIVATOR_VERSION} /var/lib/activator
chown -R ubuntu:ubuntu /var/lib/activator

echo "Instalando Grunt"
npm install -g grunt-cli
npm install -g grunt@">0.4.5"
npm install -g grunt-autoprefixer@">=3.0.3"
npm install -g grunt-contrib-jasmine
npm install -g grunt-contrib-jshint@">=0.10.0"
npm install -g grunt-contrib-less@">=1.0.1"
npm install -g grunt-contrib-uglify@">=0.8.0"
npm install -g grunt-contrib-watch@">0.6.1"
npm install -g grunt-template-jasmine-istanbul@">0.3.3"

echo "Installing openjdk 1.8.0..."
add-apt-repository -y ppa:openjdk-r/ppa
apt-get update
apt-get install -y openjdk-8-jdk
