#!/bin/bash -e

# Copyright 2015 basebuilder authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

SOURCE_DIR=/var/lib/tsuru
$SOURCE_DIR/base/install
apt-get install gcc make curl libpcre3-dev zlib1g-dev wget -y
mkdir -p /var/nginx
wget https://s3.amazonaws.com/devops-hu/home/GeoIP2-City.mmdb -P /var/nginx
wget https://s3.amazonaws.com/devops-hu/home/hu-nginx-v2.deb -P /tmp/
dpkg -i /tmp/hu-nginx-v2.deb
rm -rf /var/log/nginx /var/lib/nginx
mkdir -p /var/log/nginx /var/lib/nginx
chown -R ubuntu:ubuntu /var/lib/nginx /var/log/nginx /var/nginx
cp ${SOURCE_DIR}/static_geoip/Procfile ${SOURCE_DIR}/utils/Procfile
cp ${SOURCE_DIR}/static_geoip/etc/nginx.conf /etc/nginx/nginx.conf
echo "sudo chmod 777 /dev/stdout" >> /etc/profile
# usado para gerar os staticos
sudo npm install -g grunt-cli
sudo npm install -g bower
sudo npm install -g gulp node-gyp