#!/bin/bash -el

# Copyright 2015 basebuilder authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/deploy
APP_DIR=/home/application/current
set +e
test -e ${APP_DIR}/nginx.conf && sudo cp ${APP_DIR}/nginx.conf /etc/nginx/nginx.conf
set -e

if [ -f ${CURRENT_DIR}/package.json ]; then
    if [ -d ${CURRENT_DIR}/node_modules ]; then rm -rf ${CURRENT_DIR}/node_modules ; fi
    pushd $CURRENT_DIR && npm install
    popd
fi

if [ -f ${CURRENT_DIR}/bower.json ]; then
    pushd $CURRENT_DIR && bower install
    popd
fi
