#!/bin/bash -le

# Copyright 2015 basebuilder authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/deploy
source ${SOURCE_DIR}/config

if [ -d ${CURRENT_DIR}/node_modules ]; then
    rm -rf ${CURRENT_DIR}/node_modules ;
fi
pushd $CURRENT_DIR && npm install --production

if [ -f ${CURRENT_DIR}/bower.json ]; then
    pushd $CURRENT_DIR && bower install --production
fi
popd