#!/bin/bash -el

# Copyright 2015 basebuilder authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

chmod +s /usr/bin/sudo

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/config

mkdir -p /home/application
useradd -m ${USER} -s /bin/bash
chown ${USER}:${USER} /home/application
echo "${USER} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

cat >> /home/ubuntu/.profile <<EOF
[ -f /home/application/apprc ] && source /home/application/apprc
EOF

apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install curl git openssh-server python-virtualenv python-pip libzmq-dev g++ python-dev wget libyaml-dev -y

virtualenv ${VENV_DIR}
${VENV_DIR}/bin/pip install PyYAML==3.12 argparse==1.2.1 backports-abc==0.5 backports.ssl-match-hostname==3.5.0.1 certifi==2017.4.17 circus==0.11.1 honcho==0.5.0 iowait==0.2 measures==1.1.0 psutil==5.2.2 pyzmq==16.0.2 requests==2.13.0 semantic-version==2.4.2 singledispatch==3.4.0.3 six==1.10.0 tornado==4.5.1 tsuru-circus==0.8.18 tsuru-unit-agent==0.5.0 wsgiref==0.1.2

pip install tsuru-unit-agent==0.5.0

sed -ri 's/^session\s+required\s+pam_loginuid.so$/session optional pam_loginuid.so/' /etc/pam.d/sshd
mkdir /var/run/sshd
echo "export DEBIAN_FRONTEND=noninteractive" >> /etc/profile

mkdir -p /etc/circus /var/log/circus
cp ${SOURCE_DIR}/utils/circus.ini /etc/circus/circus.ini
chown -R ${USER}:${USER} /etc/circus /var/log/circus