#!/bin/bash -el

# Copyright 2015 basebuilder authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/deploy
source ${SOURCE_DIR}/config

echo "copiando o sbt para o bin"
sudo cp $SOURCE_DIR/scala/sbt /bin/sbt
sudo chmod 755 /bin/sbt